-- CONSULTAS PARA: CLIENTES
SELECT * FROM cliente;
DROP TABLE IF EXISTS cliente;

-- CONSULTAS PARA: CONCEPTO DE USO
SELECT * FROM concepto;
SELECT SUM(puntos) FROM concepto;
SELECT * FROM concepto WHERE descripcion ILIKE '%desc%ropa%';
DROP TABLE IF EXISTS concepto;

-- CONSULTAS PARA: REGLAS DE PUNTOS
SELECT * FROM reglas_puntos;
DROP TABLE IF EXISTS reglas_puntos;

-- CONSULTAS PARA: PARAMETRIZACION DE PUNTOS
SELECT * FROM parametrizacion_venc_puntos;
DROP TABLE IF EXISTS parametrizacion_venc_puntos;

-- CONSULTAS PARA: BOLSA DE PUNTOS
SELECT * FROM bolsa_puntos;
DROP TABLE IF EXISTS bolsa_puntos;

-- CONSULTS PARA USO DE PUNTOS:
SELECT * FROM puntos_cabecera;
