-- CONSULTAS PARA: CLIENTES
SELECT * FROM cliente;
DROP TABLE IF EXISTS cliente;

-- CONSULTAS PARA: CONCEPTO DE USO
SELECT * FROM concepto;
DROP TABLE IF EXISTS concepto;

-- CONSULTAS PARA: REGLAS DE PUNTOS
SELECT * FROM reglas_puntos;
DROP TABLE IF EXISTS reglas_puntos;

